python inference.py \
--model_name "svd" \
--control_types "segmentation" \
--segmentation_type "odise" \
--local_checkpoint_path "checkpoints/adapter_jasper" \
--eval_input_type "frames" \
--evaluation_input_folder "assets/evaluation/frames" \
--global_step 70000 \
--skip_conv_in True \
--n_sample_frames 14 \
--n_ref_frames 1 \
--num_inference_steps 25 \
--control_guidance_end 0.8 \
--use_size_512 false \
--height 360 \
--width 640 \
--evaluation_prompt_file "captions_AD_simul.json" 